export const mockDetails = [
    {assignee: 'Abhishek Garg',
        createdDate: '2020-06-10T01:09:03Z',
        department: 'EG Tech Data Rptg/BO Bellevue',
        id: 'TRANS-23297',
        l1: 'Egencia',
        l2: 'Egencia Product',
        l3: 'Egencia Tech',
        l4: 'Egencia Product and Tech',
        l5: 'Egencia Tech - Global',
        priority: 'P4 - Medium',
        projectId: '59608',
        projectName: 'Transaction Services',
        resolution: 'Fixed',
        resolvedDate: '2020-06-29T06:51:24Z',
        status: 'In Progress',
        summary: 'Enhance Trip Cloud Alerts',
        updatedDateTime: '2021-02-15T22:14:41.381656Z',
        url: 'https://jira.expedia.biz/browse/TRANS-23297'},
    {assignee: 'Abhishek Garg',
        createdDate: '2020-06-10T01:09:03Z',
        department: 'EG Tech Data Rptg/BO Bellevue',
        id: 'TRANS-23298',
        l1: 'Egencia - Consolidated',
        l2: 'Egencia Product and Tech',
        l3: 'Egencia Tech - Global',
        l4: 'Egencia Product and Tech',
        l5: 'Egencia Tech - Global',
        priority: 'P4 - Medium',
        projectId: '59608',
        projectName: 'Transaction Services',
        resolution: 'Fixed',
        resolvedDate: '2020-06-29T06:51:24Z',
        status: 'Done',
        summary: 'Enhance Trip Cloud Alerts',
        updatedDateTime: '2021-02-15T22:14:41.381656Z',
        url: 'https://jira.expedia.biz/browse/TRANS-23298'},
    {assignee: 'Abhishek Garg',
        createdDate: '2020-06-10T01:09:03Z',
        department: 'EG Tech Data Rptg/BO Bellevue',
        id: 'TRANS-23299',
        l1: 'Egencia - Consolidated',
        l2: 'Egencia Product and Tech',
        l3: 'Egencia Tech - Global',
        l4: 'Egencia Product and Tech',
        l5: 'Egencia Tech - Global',
        priority: 'P4 - Medium',
        projectId: '59608',
        projectName: 'Transaction Services',
        resolution: 'Fixed',
        resolvedDate: '2020-06-29T06:51:24Z',
        status: 'Done',
        summary: 'Enhance Trip Cloud Alerts',
        updatedDateTime: '2021-02-15T22:14:41.381656Z',
        url: 'https://jira.expedia.biz/browse/TRANS-23299'},
];