exports.RC_PORTFOLIOS = 'All RootCause Portfolios';
exports.RC_PORTFOLIO_GROUPS = 'All RootCause Portfolio Groups';
exports.IMPACTED_PORTFOLIOS = 'All Impacted Portfolios';
exports.IMPACTED_PORTFOLIO_GROUPS = 'All Impacted Portfolio Groups';
exports.DATE_FORMAT = 'YYYY-MM-DD';
exports.P1_PRIORITY = 'P1 - Blocker';
exports.P2_PRIORITY = 'P2 - Major';
exports.ALL_P1_P2 = 'All - P1 & P2';
exports.FETCH_OPTION = {Accept: 'application/json', 'Content-Type': 'application/json'};
